---
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: extract artifact into ec2 instance
  ansible.builtin.unarchive:
    src: artifact.tar.gz
    dest: ~/web

- name: start server
  shell: |
    cd ~/web
    npm install
    pm2 stop default
    sudo pm2 start npm -- start
